### ISSUE TITLE
Installing yoyoloader? on the homebrew app?

### ISSUE THREAD

**Issue by MUGENPSVITA** [Rinnegatamante/yoyoloader_vita#1]
So i installed the yoyoloader from the homebrew browser and installed the 2 plugins kubridge and FdFix from auto plugin 2 but it didn't work instead an error loaded up that says 
(C2-12828-1) 
saved core file succeeded 
ux0:data/psp2core-16495846190-0x00000a3a11-eboot.bin.psp2dmp
plz help 
i'm on cfw 3.65

**Comment by Rinnegatamante** [comment]
You need libshacccg and at least a game installed in the loader.
