### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by rodentcat** [Rinnegatamante/yoyoloader_vita#100]
Hi there, after updating I've been dealing with an error on startup. I've tried uninstalling and reinstalling several times, nothing works. I'm wondering if it's an issue on my end or if it's something that needs fixing.

The error is C2-12828-1.

**Comment by jbanks844** [comment]
I'm having the same problem. I downloaded through homebrew then tried following the manual instructions but Its still the same message

**Comment by Held-der-Arbeit22** [comment]
Same here.With the newest update I get an instant crash.Tried out with 2 different Vitas.

**Comment by Rinnegatamante** [comment]
Can you guys download these two files:
https://github.com/CelesteBlue-dev/PSVita-RE-tools/blob/master/vita-unmake-fself/release/vita-unmake-fself.exe
https://github.com/CelesteBlue-dev/PSVita-RE-tools/blob/master/nids-extract/build/nids-extract.exe

Get your extracted libshacccg.suprx file from ur0:data to your PC and then run from a command line:
vita-unmake-fself libshacccg.suprx
nids-extract 3.60 libshacccg.suprx.elf

and report the results?

**Comment by Rinnegatamante** [comment]
If nids-extract fails, try with this version: [nids-extract.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/8929764/nids-extract.zip)

**Comment by Rinnegatamante** [comment]
Should be fixed now. Can anyone of you report me if it effectively is?

**Comment by Held-der-Arbeit22** [comment]
Yes,works again.Thank you

**Comment by MystiK791** [comment]
@Rinnegatamante I'm having the same issue with a built YYL VPK. I'm on 3.65, is that an issue?
