### ISSUE TITLE
Exit the game with the game's own option

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/yoyoloader_vita#101]
Previously it was possible to exit a game using the game's own option (without using the button combinations), but now it is no longer possible.
If you press the exit option, nothing happens. in "Juiced!" for example, the option disappears when you press it.
Is it possible to fix it?

**Comment by Rinnegatamante** [comment]
If the game is an Android native one, such thing won't and will never work since Android runner doesn't implement such feature.
