### ISSUE TITLE
HoloCure [HoloCure] - Unable to load VPK Bubble

### ISSUE THREAD

**Issue by DRok17** [Rinnegatamante/yoyoloader_vita#112]
VPK goes into error after the splash screen. Asset folder remains empty

Crash dump, log, and cfg files are attached:

[HOLOCURE0.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/9108408/HOLOCURE0.zip)

The game works fine when launched thru the application using the same config.

**Comment by Rinnegatamante** [comment]
This is not compatibility list.
