### ISSUE TITLE
vita on-screen keyboard in yoyoloader

### ISSUE THREAD

**Issue by BrickCrypt** [Rinnegatamante/yoyoloader_vita#114]
I wanted to know if its possible to add the Vita on-screen keyboard
Undertale PSVITA version
![ezgif-3-820404302f](https://user-images.githubusercontent.com/104641878/180302355-8361ece1-d6c7-496c-90bc-2f478a2a2ab2.gif)

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/yoyoloader_vita/blob/main/loader/main.c#L1867-L1871 Yes

**Comment by BrickCrypt** [comment]
> https://github.com/Rinnegatamante/yoyoloader_vita/blob/main/loader/main.c#L1867-L1871 Yes

Sorry but I don't get the virtual keyboard with Super Mario Maker WE and others, am I missing a plugin? i have fd_fix, kubridge and revita
It only works for me when I pass it to a bubble but I saw that others get it in the yoyoloader

**Comment by Rinnegatamante** [comment]
Probably your launching options. You must not have Squeeze Mem.
