### ISSUE TITLE
run YoyoLoader on Shield tv

### ISSUE THREAD

**Issue by Liquidgykill** [Rinnegatamante/yoyoloader_vita#12]
Would be possible to run Yoyoloader on Shield tv for games like AM2R that are locked on android devices like shield?

**Comment by Rinnegatamante** [comment]
YoYo Loader is wrote specifically for Vita but a similar approach can be done for Android I guess. @JohnnyonFlame worked prior to YoYo Loader to a similar approach but for Linux for example ( https://github.com/JohnnyonFlame/droidports/tree/master/ports/gmloader ).

**Comment by JohnnyonFlame** [comment]
> Would be possible to run Yoyoloader on Shield tv for games like AM2R that are locked on android devices like shield?

Likely some work needs to be done to spoof the game into believing it's compatible and introducing any possible missing bit - maybe controller support etc, but that's a bit far from "running yoyoloader on shield tv".

I don't have a Shield TV nor do I plan on having one, this is probably best asked on Reddit or xda-developers.
