### ISSUE TITLE
Crash on startup despite working earlier 

### ISSUE THREAD

**Issue by trainman313** [Rinnegatamante/yoyoloader_vita#123]
I was playing games on yoyo loader fine a couple of hours earlier. Now when I open yoyo loader it gives me the error C2-12828-1.

**Comment by momokaze** [comment]
Hmm, same as me.
After downloading database 10/10, the app crashed.
I am using autoplugin 2, to install kubridge, fd_fix and libshacccg from sharkfood.
Then uninstalled it before opening it.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/yoyoloader_vita/commit/c1f080670ac02c17e8f9dc17c1fd2055bebe0531
