### ISSUE TITLE
YYZ Support

### ISSUE THREAD

**Issue by MystiK791** [Rinnegatamante/yoyoloader_vita#128]
Hello there! I wonder if it would be possible to support the YYZ format for YoYoLoader, so that people without an export license can make games? Alternatively, is there any way to asset-swap only with a YYZ file?

(Sorry if this is a stupid question, I'm pretty new to Gamemaker lol).

Thanks!

**Comment by m1s3ry** [comment]
.YYZ is an exported source project file, it's not a compiled game, so you can't run it unless you compile it.

If you don't have an export license you can probably still build your game for PC and then get the temp files from appdata folder.

**Comment by MystiK791** [comment]
I think I'll try that. Thanks!
