### ISSUE TITLE
Problems with latest version

### ISSUE THREAD

**Issue by Laummie** [Rinnegatamante/yoyoloader_vita#137]
Hello before Arcana Soul was running without any problem after an automatic update I can't get it running anymore, also Luigi's mansion 2d same story.

**Comment by Rinnegatamante** [comment]
Post logs on the related compatibility list entries for those games.

**Comment by Laummie** [comment]
Luigi's mansion 2d crashes
Arcana soul sends back to livearea
[arcane soul yyl.log](https://github.com/Rinnegatamante/yoyoloader_vita/files/12782492/arcane.soul.yyl.log)
[luigi mansion 2d yyl.log](https://github.com/Rinnegatamante/yoyoloader_vita/files/12782497/luigi.mansion.2d.yyl.log)

**Comment by Laummie** [comment]
When you have some spare time can you please solve these problems
