### ISSUE TITLE
Disable auto-update and DB update check?

### ISSUE THREAD

**Issue by Darthagnon** [Rinnegatamante/yoyoloader_vita#142]
Every time I launch Yoyo loader, instead of being able to play a game, it has to go through checking for updates and redownloading compatibility database (even when offline). Is there a way to disable this feature and only check manually? I'd rather just get to the game list and play.

**Comment by Rinnegatamante** [comment]
I can add a combination of keys to press at boot in order to skip them if that would suffice.

**Comment by Darthagnon** [comment]
> I can add a combination of keys to press at boot in order to skip them if that would suffice.

That would be awesome! Or would it be possible to add keys to press in order to trigger them?

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/yoyoloader_vita/commit/eafe251a185c98dcd0f3c0a1c5e0e70606890982 . Will be available soon on Nightly.

**Comment by Darthagnon** [comment]
Thank you so much! 🖖
