### ISSUE TITLE
Translate Yoyo-Loader?

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/yoyoloader_vita#17]
Would it be possible? I can collaborate with the Spanish language :)

**Comment by Rinnegatamante** [comment]
Translations are now available ( https://github.com/Rinnegatamante/yoyoloader_vita/commit/e33c687fc7c55164998694a8503a268e696f1258 ).
You can find a file with all the strings to translate here: https://github.com/Rinnegatamante/yoyoloader_vita/blob/main/translations/English.ini

**Comment by SofyUchiha** [comment]
@Rinnegatamante I think it is ready. I did a new version in Spanish, since the current one has many orthographic errors and distance itself from what is written in English, I hope it can be served! Thank you!
https://github.com/SofyUchiha/yoyoloader_vita/blob/patch-1/translations/Spanish%20(v.2).ini
