### ISSUE TITLE
Super Mario Maker World Engine [SMM_WE] - Unable to load VPK Bubble

### ISSUE THREAD

**Issue by DRok17** [Rinnegatamante/yoyoloader_vita#18]
VPK goes into error after the splash screen.

![2022-04-22-221543-972343](https://user-images.githubusercontent.com/81541725/164866030-3eb75792-7acb-4684-bdc7-cedf0f9abf9a.png)

Asset folder remains empty:

![2022-04-22-221220-199711](https://user-images.githubusercontent.com/81541725/164866127-6a287c69-42c3-4f41-878b-5106707b2cfd.png)

Crash dump, log, and cfg files are attached:

[psp2core-1650678943-0x00014b277b-eboot.bin.psp2dmp.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/8545965/psp2core-1650678943-0x00014b277b-eboot.bin.psp2dmp.zip)

The game works fine when launched thru the application using the same config.

**Comment by Rinnegatamante** [comment]
Should be fixed with https://github.com/Rinnegatamante/yoyoloader_vita/commit/7cd6204684f168097913f8eadcf4ccba1dcba32e

**Comment by DRok17** [comment]
Tested and fixed. Thanks!
