### ISSUE TITLE
Can I collaborate? I made some banners

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/yoyoloader_vita#21]
- Alien Escape [AlienEscape]
![image](https://user-images.githubusercontent.com/70182567/164959320-6dbf8f6f-7201-486f-8a1b-30c3ad833946.png)

- Blue Bayou [gbjam]
![image](https://user-images.githubusercontent.com/70182567/164959264-6610facb-f2fb-423b-96de-572407d65d69.png)

- Pix Hop [pixhop_gms2_1030]
![image](https://user-images.githubusercontent.com/70182567/164959280-3f4feba8-4a6b-4675-94b5-64ac2ff3a1f3.png)

- Super Chicken Jumper [superchickenjumper versao 23]
![image](https://user-images.githubusercontent.com/70182567/164959284-7b5bd050-586f-4313-83ba-fc0a9f712cc2.png)

- WIZ [WIZ_MOBILE]
![image](https://user-images.githubusercontent.com/70182567/164959291-9fbe3f81-e432-43bb-a10e-f7c7fcdb4d96.png)

I have tested them, and it works fine! I attach a .zip file with the images
[Banners.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/8549103/Banners.zip)

**Comment by Rinnegatamante** [comment]
Open a Pull Request to add them. They are here: https://github.com/Rinnegatamante/yoyoloader_vita/tree/main/banners

**Comment by SofyUchiha** [comment]
> Open a Pull Request to add them. They are here: https://github.com/Rinnegatamante/yoyoloader_vita/tree/main/banners

Honestly, I don't know how to do it (I'll learn, I promise) but I'm scared to do it and screw up. Meanwhile, I'll work on the translation in my free time <3

**Comment by Rinnegatamante** [comment]
Pushed them however run pngquant on your images before submitting them.
