### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by kuragehimekurara1** [Rinnegatamante/yoyoloader_vita#27]
I would like to translate YoYo Loader Vita into Japanese. Does YoYo Loader Vita support translation?

**Comment by Rinnegatamante** [comment]
Yes, can be found here: https://github.com/Rinnegatamante/yoyoloader_vita/tree/main/translations

**Comment by kuragehimekurara1** [comment]
> Yes, can be found here: https://github.com/Rinnegatamante/yoyoloader_vita/tree/main/translations

Should I translate an English file into Japanese?
