### ISSUE TITLE
Sorry but... how do i update yoyo_loader?

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/yoyoloader_vita#3]
with the commits that are coming out for the games to run? or the app is updated automatically when you start it?
Excuse my ignorance... You are a genius, thanks for your work!

**Comment by maddie1268991** [comment]
It automatically checks for and installs updates each time you start it

**Comment by SofyUchiha** [comment]
Okay. What happens when you start the app, it always stays in the same version. Now I reinstalled and updated! thanks!
