### ISSUE TITLE
Is there a way to change games without leaving Yoyo-loader?

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/yoyoloader_vita#4]
Is it possible to change games without having to close yoyo-loader every time? Some combination of buttons?
If not, is it possible to add that option in future projects? Thanks!

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/yoyoloader_vita/commit/c10606036a36bb1d8dfdbb7e63abf01144a6eea1
