### ISSUE TITLE
KeyMaps - "C" Key not working

### ISSUE THREAD

**Issue by DRok17** [Rinnegatamante/yoyoloader_vita#48]
Buttons that use Windows "C" do not register. Keycodes 0-255 were tried and did not work.

Recent game I've tried was Megaman X Engine. All other buttons I've mapped out work on PC version other than "C".

[keys-cfg.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/8645763/keys-cfg.zip)

[yyl.log](https://github.com/Rinnegatamante/yoyoloader_vita/files/8645761/yyl.log)

**Comment by SofyUchiha** [comment]
Same for the game: JackQuest: The Tale of The Sword, It's impossible to do the spin attack. Only normal is possible

**Comment by DRok17** [comment]
Yes, Jack Quest and Luigi's Mansion 2d also have this issue.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/yoyoloader_vita/commit/1881696151b4c92033596b506f64238fca0f1a85

**Comment by DRok17** [comment]
Fixed for JackQuest and MMXE, but not for Luigi's Mansion 2D. I don't think this should be re-opened tho.
