### ISSUE TITLE
App crashes when starting a game via app params

### ISSUE THREAD

**Issue by cy33hc** [Rinnegatamante/yoyoloader_vita#5]
I have uploaded the AM2R 1.5.5 apk at the following path
ux0:data/gms/AM2R/game.apk

Starting the game from YoYo Launcher GUI, the game starts up fine.

Created a VPK using the bubble builder and installed it. After starting the bubble for about 1-2 sec, the app crashes.

The debug yy.log file doesn't even get created.

**Comment by cy33hc** [comment]
Looking at the code, the name of the game should be written to the file launch.txt. But the launch.txt actually contains garbage characters in it.

**Comment by cy33hc** [comment]
@Rinnegatamante Is there a reason for removing the ability to launch app using BootParams? I would like the keep the apk in the ux0:data/gms folder so it can be shared with the YoYo Launcher app.

**Comment by Rinnegatamante** [comment]
Wasn't it not working? By the way, i guess i can re-add it if needed.

**Comment by Rinnegatamante** [comment]
I've added it back. Going to close this issue since now the old custom bubble builder is superseeded by the new one bundling the loader inside the produced vpk.

**Comment by cy33hc** [comment]
@Rinnegatamante Hi Rinnegatemante, can you reopen this bug. Thx for add this option back, but it is still broken. The app is not writing the game_name properly into the ux0:data/gms/launch.txt. It's always writing 4bytes of garbage chars into the file instead of the game name. Only happens when passing in boot_params. It looks like it's write a memory address instead of the game name.

**Comment by Rinnegatamante** [comment]
It's using same code of DaedalusX64, i can't see what's wrong...

**Comment by cy33hc** [comment]
Nevermind. I'll just use the current bubble builder.
