### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by ikzouo** [Rinnegatamante/yoyoloader_vita#59]
Hello developer . Here is my Chinese translation file.  Could you add him to the program.Thanks
[Simplified Chinese.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/8694185/Simplified.Chinese.zip)

**Comment by Rinnegatamante** [comment]
Integrated with https://github.com/Rinnegatamante/yoyoloader_vita/commit/672d204e28d6f4b2ac799c5eaf4947ac03693be5 .
Thanks.

**Comment by ikzouo** [comment]
Thanks for your help I am very happy(•ᴗ•)

**Comment by Rinnegatamante** [comment]
There are a couple new lines to update with latest updates if you want to send those lines as well.

**Comment by ikzouo** [comment]
Hi. I adjusted the simplified Chinese translation and added the traditional translation file . 
[Chinese.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/8695609/Chinese.zip)

**Comment by ikzouo** [comment]
> There are a couple new lines to update with latest updates if you want to send those lines as well.

Hi. I adjusted the simplified Chinese translation and added the traditional translation file . @Rinnegatamante
[Chinese.zip](https://github.com/Rinnegatamante/yoyoloader_vita/files/8695623/Chinese.zip)
