### ISSUE TITLE
Remap Left and Right Mouse Click Input

### ISSUE THREAD

**Issue by CatoTheYounger97** [Rinnegatamante/yoyoloader_vita#68]
Ability to remap "left mouse click" and "right mouse click" to other buttons on the vita game pad. 

This would benefit the control schemes of the following games:
-Post Void: https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/100
-Madness:Off Color: https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/160
-Star VS The Game: https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/340
-Windowframe: https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/123

**Comment by Rinnegatamante** [comment]
Left mouse click now possible with https://github.com/Rinnegatamante/yoyoloader_vita/commit/e4804250a3253ce56da655f30d4ee25943fba035
