### ISSUE TITLE
please fix the touchscreen

### ISSUE THREAD

**Issue by tehrayma** [Rinnegatamante/yoyoloader_vita#86]
yoyo loader got updated in my ps vita, yeah it's obvious and fine, and i started a game like Sonic Time Twisted, but every time i tried to scroll down the options, it just clicked into video mode or sound mode instead, and i've tried "everything" (reinstalling it, deleting the shared folder and some other things on the games, uninstalling revita and revitamotion plugin(s) and it DIDN'T do that before the update, It wasn't just sonic time twisted, it also was super mario maker world engine and super mario 4 jugadores :/

**Comment by tehrayma** [comment]
is there a way to downgrade to an older version of yoyo loader?

**Comment by Rinnegatamante** [comment]
Pushed a fix for it.
