### ISSUE TITLE
Suggestion of compatible Android application (Game Streaming, PLEX and Chrome)

### ISSUE THREAD

**Issue by MaitreAnonyme** [Rinnegatamante/yoyoloader_vita#91]
Hello, Since I discovered your emulator apk. I would like to offer you some apks to make them compatible with your emulator.

Game Streaming :
- PSPlay (Paid) or PS Remote Play (Stream PS5) [PS Remote Play only supports Dualshock 4/Dualsense, not PS Vita Gamepad. It may be possible on PSTV with a DualShock 4 or on a PS Vita with the ds34vita plugin. On PSPlay, you can manually configure any controller.]
- XBOX App (Stream XBOX ONE/SERIE) [With the X1Vita or ds34vita Plugin]
- XBOX Game Pass [With the X1Vita or ds34vita Plugin]
- Stadia [With the X1Vita or ds34vita Plugin]
- Nvidia GeForce NOW [With the X1Vita or ds34vita Plugin]

Video Service :
- PLEX (Paid on the app or by subscription)
- Chrome (For Netflix, Disney+, Amazon Prime Video, other)

If these apks are compatible with the emulator. So I believe that the console will have reached its potential (in my opinion).

**Comment by ToastyCheese** [comment]
This is a GameMaker Studio games loader,not
 a Android Emulator
