### ISSUE TITLE
Game quit bug

### ISSUE THREAD

**Issue by ikzouo** [Rinnegatamante/yoyoloader_vita#94]
When I click the quit  option in the game, the software enters a suspended state and I have to restart the software to exit,the game's settings are also initialized.

This is the apk I use https://drive.google.com/file/d/1WXiy3RCafz6VgA2Avq---lSH5jySw_YC/view?usp=sharing

I optimized the APK and turned on these options
*Fake Windows as Platform  
*Run with Extended Mem Mode
*Run with Extended Runner Pool

In addition to the above problems, I have to restart the software every time I switch games. Would you mind optimizing it? Thanks

**Comment by Rinnegatamante** [comment]
This is not compatibility list.

**Comment by ikzouo** [comment]
> This is not compatibility list.

OK
